name: Build and publish

on:
  workflow_dispatch:

jobs:
  validate:
    name: Build and publish code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Run Git Fetch
        id: git_fetch_run
        run: |
          git fetch --prune
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Set Git user
        run: |
          git config --global user.name "kokofixcomputers-bot"
          git config --global user.email "kokobot@kokofixcomputers.serv00.net"
      - name: Check types and Build
        run: yarn tsc --noEmit && NODE_ENV=PRODUCTION yarn run build
      - name: Pack Chrome Extension
        run: yarn run extension:pack
      - name: Upload Userscript And Extension
        uses: actions/upload-artifact@v3
        with:
          name: Userscript and Unpacked Extension
          path: |
            dist/eureka-loader.user.js
            dist/unpacked-extension.zip
      - name: Get Version from package.json
        id: package_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Copy eureka-loader.user.js to repo
        run: |
          cp dist/eureka-loader.user.js .
          git add eureka-loader.user.js
          git commit -m "Update eureka-loader.user.js"
          git push
      - name: Comment on Commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.KOKOBOT_TOKEN }}
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: 'Build Succeeded!'
            })
      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.KOKOBOT_TOKEN }}
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');

            const version = '${{ steps.package_version.outputs.version }}';
            const releaseBody = execSync('git log --pretty=format:"%h: %s (%an)" --reverse').toString();

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              name: `Release ${version}`,
              body: releaseBody,
              draft: false,
              prerelease: false
            });

            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: 'eureka-loader.user.js',
              data: fs.readFileSync('eureka-loader.user.js')
            });

            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: 'unpacked-extension.zip',
              data: fs.readFileSync('dist/unpacked-extension.zip')
            });
